version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - prealloc
    - ineffassign
    - gocritic
    - gosec
    - unconvert
    - unparam
    - wastedassign
    - govet
    - gocyclo
    - dupl
    - gocognit
    - nestif
    - funlen
    - cyclop
    - misspell
    - nakedret
    - goconst
    - exhaustive
    - errorlint
    - gomodguard
    - godox
    - makezero
    - thelper
    - tparallel
    - whitespace
    - perfsprint
    - sqlclosecheck
    - rowserrcheck
    - contextcheck
    - containedctx
    - interfacebloat
    - sloglint
    - spancheck
    - usestdlibvars
    - predeclared
    - nolintlint
    - nilnil
    - nilerr
    - forcetypeassert
    - varnamelen
    - wrapcheck
    - paralleltest
    - reassign
    - nonamedreturns
  settings:
    staticcheck:
      checks: ["all"]
    gosec:
      excludes:
        - G104
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 20
    nestif:
      min-complexity: 4
    funlen:
      lines: 90
      statements: 50
    cyclop:
      max-complexity: 15
  exclusions:
    presets: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
  settings:
    goimports:
      local-prefixes: [github.com/aclfe/gorgon]