version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - modernize
    - revive
    - misspell
    - nakedret
    - nilerr
    - unparam
    - prealloc
    - unconvert

  settings:
    staticcheck:
      checks: ["all"]
    gosec:
      excludes:
        - G104
    revive:
      enable-all-rules: true
      rules:
        - name: bare-return
          disabled: true
    errcheck:
      check-type-assertions: true
      check-blank: true

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes: [github.com/aclfe/gorgon]