version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - prealloc
    - ineffassign
    - gocritic
    - gosec
    - unconvert
    - unparam
    - wastedassign
    - staticcheck
    - govet
    - errcheck
    - gocyclo
    - dupl
    - gocognit
    - nestif
    - funlen
    - cyclop
    - misspell
    - revive
    - nakedret
    - goconst
    - exhaustive
    - errorlint
    - gomodguard
    - godox
    - makezero
    - thelper
    - tparallel
    - whitespace
    - perfsprint
    - sqlclosecheck
    - rowserrcheck
    - contextcheck
    - containedctx
    - interfacebloat
    - sloglint
    - spancheck
    - usestdlibvars
    - predeclared
    - nolintlint
    - nilnil
    - nilerr
    - forcetypeassert
    - varnamelen
    - wrapcheck
    - paralleltest
    - testpackage
    - reassign
    - nonamedreturns
  settings:
    staticcheck:
      checks: ["all"]
    gosec:
      excludes:
        - G104
    revive:
      enable-all-rules: true
      rules:
        - name: bare-return
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: cognitive-complexity
          arguments: [15]
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          arguments: [50, 0]
        - name: max-public-structs
          arguments: [10]
        - name: line-length-limit
          arguments: [120]
        - name: add-constant
          arguments:
            - maxLitCount: "5"
              allowInts: "0,1,2"
              allowStrs: '""'
              allowFloats: "0.0"
        - name: deep-exit
          disabled: true
    errcheck:
      check-type-assertions: false
      check-blank: true
    gocyclo:
      min-complexity: 15
    gocognit:
      min-complexity: 20
    nestif:
      min-complexity: 4
    funlen:
      lines: 90
      statements: 50
    cyclop:
      max-complexity: 15
  exclusions:
    presets: []  # Empty list to replicate exclude-use-default: false (no default exclusions)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
    - gofumpt
    - gci
  settings:
    goimports:
      local-prefixes: [github.com/aclfe/gorgon]